### ISSUE TITLE
Ctrl-P issue

### ISSUE THREAD

**Issue by oldtimeguitarguy** [sickill/vim-pasta#12]
Vim pasta is attempting to paste into the Ctrl-P file list when Ctrl-P is open. Since that buffer is write protected, it creates an error and will not allow me to type the letter "p". Is there a way to prevent this without changing the key bindings?

**Comment by sickill** [comment]
I've been using vim-pasta together with ctrl-p and never experienced this problem 🤔

**Comment by oldtimeguitarguy** [comment]
I think I figured it out - it was because of some mappings I had. Sorry!

**Comment by oldtimeguitarguy** [comment]
Actually I was wrong - it didn't have anything to do with mappings. It only happens after I use another plugin: https://github.com/tacahiroy/ctrlp-funky

Once I do that, for some reason, p tries to paste in regular ctrlp
