### ISSUE TITLE
vim-pasta makes neovim hang on pasting large content via terminal paste functionality

### ISSUE THREAD

**Issue by mqudsi** [sickill/vim-pasta#13]
I'm not sure if there's anything that can be done about it, but attempting to paste a large buffer via the terminal paste functionality (as opposed to via the system clipboard register) with vim-pasta loaded makes neovim hang indefinitely.

Without vim-pasta, the paste happens virtually instantly. 
This is under the Windows terminal conhost.exe under Windows 10 build 15063.

This is what I had copied to the system clipboard: http://termbin.com/ubx1

**Comment by sickill** [comment]
Hey @mqudsi, thanks for the report. What about classic vim? Does the issue happen there too?

**Comment by mqudsi** [comment]
Sorry I never got around to replying, but I don't use stock vim with plugins so I couldn't tell you.

However, I did recently re-experience this with neovim despite having disabled vim-pasta since the time I filed this issue; so it seems that vim-pasta exacerbates a neovim bug but isn't actually culpable for this behavior.

**Comment by sickill** [comment]
Thanks for the update 👍
