### ISSUE TITLE
vim-pasta interferes with NERDTree `p` (go to parent node)

### ISSUE THREAD

**Issue by ryrych** [sickill/vim-pasta#9]
Is is possible to disable vim-pasta `p` command in certain contexts / plugins? This is what I get:

```
Error detected while processing function <SNR>79_NormalPasta:
line   13:
E21: Cannot make changes, 'modifiable' is off
E21: Cannot make changes, 'modifiable' is off
Press ENTER or type command to continue
```

**Comment by sickill** [comment]
Yeah, I noticed the same recently (after I updated NERDTree to latest version). Frankly, I'm not sure how to detect this. Maybe there is a way to check buffer type?

**Comment by ryrych** [comment]
I don't know either - I've using Vim for less than 6 months so I don't have much experience.

**Comment by ptzz** [comment]
Adding `let g:pasta_disabled_filetypes = ['nerdtree']` to `.vimrc` did the trick for me.

**Comment by sickill** [comment]
I have added `nerdtree` to default disabled filetypes in 45900f1 . Thanks @ptzz!

**Comment by ryrych** [comment]
Thanks @ptzz @sickill
